import type { Courthouse, Rating, User, Provincia } from "./types";

export const mockUsers: User[] = [
  {
    id: 'user-admin',
    nombre: 'Admin',
    apellido: 'Principal',
    email: 'admin@example.com',
    matricula: 'T0 F0',
    role: 'admin',
    status: 'approved',
  },
  {
    id: 'user-1',
    nombre: 'Juan',
    apellido: 'Perez',
    email: 'juan.perez@example.com',
    matricula: 'T123 F45',
    role: 'user',
    status: 'approved',
  },
  {
    id: 'user-2',
    nombre: 'Maria',
    apellido: 'Gomez',
    email: 'maria.gomez@example.com',
    matricula: 'T987 F65',
    role: 'user',
    status: 'pending',
  },
];

export const mockProvincias: Provincia[] = [
  { id: 1, nombre: 'Buenos Aires' },
  { id: 2, nombre: 'Catamarca' },
  { id: 3, nombre: 'Chaco' },
  { id: 4, nombre: 'Chubut' },
  { id: 5, nombre: 'Ciudad Autónoma de Buenos Aires' },
  { id: 6, nombre: 'Corrientes' },
  { id: 7, nombre: 'Córdoba' },
  { id: 8, nombre: 'Entre Ríos' },
  { id: 9, nombre: 'Formosa' },
  { id: 10, nombre: 'Jujuy' },
  { id: 11, nombre: 'La Pampa' },
  { id: 12, nombre: 'La Rioja' },
  { id: 13, nombre: 'Mendoza' },
  { id: 14, nombre: 'Misiones' },
  { id: 15, nombre: 'Neuquén' },
  { id: 16, nombre: 'Río Negro' },
  { id: 17, nombre: 'Salta' },
  { id: 18, nombre: 'San Juan' },
  { id: 19, nombre: 'San Luis' },
  { id: 20, nombre: 'Santa Cruz' },
  { id: 21, nombre: 'Santa Fe' },
  { id: 22, nombre: 'Santiago del Estero' },
  { id: 23, nombre: 'Tierra del Fuego' },
  { id: 24, nombre: 'Tucumán' },
  { id: 25, nombre: 'Justicia Federal' },
  { id: 26, nombre: 'Justicia Nacional' },
];

export const mockCourthouses: Courthouse[] = [
  {
    id: "juz-civ-1-caba",
    nombre: "Juzgado Nacional de 1ª Instancia en lo Civil Nº 1",
    provincia: "Ciudad Autónoma de Buenos Aires",
    ciudad: "CABA",
    fuero: "Civil",
    instancia: "Primera Instancia",
    direccion: "Talcahuano 550, Piso 3",
    telefono: "(011) 4371-1234",
  },
  {
    id: "juz-com-2-caba",
    nombre: "Juzgado Nacional de 1ª Instancia en lo Comercial Nº 2",
    provincia: "Ciudad Autónoma de Buenos Aires",
    ciudad: "CABA",
    fuero: "Comercial",
    instancia: "Primera Instancia",
    direccion: "Marcelo T. de Alvear 1840, Piso 2",
    telefono: "(011) 4813-5678",
  },
  {
    id: "juz-lab-3-cordoba",
    nombre: "Juzgado de Conciliación y Trabajo de 3ª Nominación",
    provincia: "Córdoba",
    ciudad: "Córdoba",
    fuero: "Laboral",
    instancia: "Primera Instancia",
    direccion: "Arturo M. Bas 150",
    telefono: "(0351) 422-9876",
  },
  {
    id: "juz-pen-4-rosario",
    nombre: "Juzgado de 1ª Instancia en lo Penal de Sentencia Nº 4",
    provincia: "Santa Fe",
    ciudad: "Rosario",
    fuero: "Penal",
    instancia: "Primera Instancia",
    direccion: "Moreno 1050",
    telefono: "(0341) 472-1111",
  },
    {
    id: "cam-fed-5-mendoza",
    nombre: "Cámara Federal de Apelaciones de Mendoza",
    provincia: "Mendoza",
    ciudad: "Mendoza",
    fuero: "Federal",
    instancia: "Cámara",
    direccion: "España 123",
    telefono: "(0261) 449-5500",
  },
];

export const mockRatings: Rating[] = [
  {
    id: "rating-1",
    juzgadoId: "juz-civ-1-caba",
    usuarioId: "user-1",
    puntuaciones: {
      calidadResoluciones: 8,
      rapidezResoluciones: 6,
      rapidezDespacho: 7,
      atencionMesaEntradas: 9,
      tratoProfesional: 8,
      puntualidadAudiencias: 7,
      ordenGeneral: 6,
      tecnologia: 8,
      practicidad: 7,
      capacitacionPersonal: 8,
    },
    comentario: "Excelente atención por parte del personal de mesa de entradas. El proceso fue más rápido de lo esperado.",
    fechaExperiencia: "2023-10-15T00:00:00.000Z",
    fechaCalificacion: "2023-10-20T00:00:00.000Z",
    status: 'approved',
  },
  {
    id: "rating-2",
    juzgadoId: "juz-civ-1-caba",
    usuarioId: "user-admin",
    puntuaciones: {
      calidadResoluciones: 4,
      rapidezResoluciones: 2,
      rapidezDespacho: 3,
      atencionMesaEntradas: 6,
      tratoProfesional: 5,
      puntualidadAudiencias: 4,
      ordenGeneral: 4,
      tecnologia: 5,
      practicidad: 6,
      capacitacionPersonal: 4,
    },
    comentario: "Mucha demora en la resolución de expedientes simples. La organización interna parece caótica.",
    fechaExperiencia: "2023-09-01T00:00:00.000Z",
    fechaCalificacion: "2023-09-05T00:00:00.000Z",
    status: 'approved',
  },
  {
    id: "rating-3",
    juzgadoId: "juz-com-2-caba",
    usuarioId: "user-1",
    puntuaciones: {
      calidadResoluciones: 10,
      rapidezResoluciones: 10,
      rapidezDespacho: 9,
      atencionMesaEntradas: 10,
      tratoProfesional: 10,
      puntualidadAudiencias: 10,
      ordenGeneral: 9,
      tecnologia: 10,
      practicidad: 9,
      capacitacionPersonal: 10,
    },
    comentario: "Un juzgado modelo. Eficientes, organizados y con un trato impecable. Resoluciones en tiempo récord.",
    fechaExperiencia: "2023-11-02T00:00:00.000Z",
    fechaCalificacion: "2023-11-03T00:00:00.000Z",
    status: 'approved',
  },
  {
    id: "rating-4",
    juzgadoId: "juz-lab-3-cordoba",
    usuarioId: "user-admin",
    puntuaciones: {
      calidadResoluciones: 6,
      rapidezResoluciones: 4,
      rapidezDespacho: 5,
      atencionMesaEntradas: 8,
      tratoProfesional: 7,
      puntualidadAudiencias: 6,
      ordenGeneral: 6,
      tecnologia: 5,
      practicidad: 7,
      capacitacionPersonal: 6,
    },
    comentario: "El personal es amable, pero los tiempos procesales son muy largos. La infraestructura es un poco antigua.",
    fechaExperiencia: "2023-08-20T00:00:00.000Z",
    fechaCalificacion: "2023-08-21T00:00:00.000Z",
    status: 'pending',
  },
];
