import type { Courthouse, Rating } from "./types";

export const mockCourthouses: Courthouse[] = [
  {
    id: "juz-civ-1-caba",
    nombre: "Juzgado Nacional de 1ª Instancia en lo Civil Nº 1",
    provincia: "Ciudad Autónoma de Buenos Aires",
    ciudad: "CABA",
    fuero: "Civil",
    instancia: "Primera Instancia",
    direccion: "Talcahuano 550, Piso 3",
    telefono: "(011) 4371-1234",
  },
  {
    id: "juz-com-2-caba",
    nombre: "Juzgado Nacional de 1ª Instancia en lo Comercial Nº 2",
    provincia: "Ciudad Autónoma de Buenos Aires",
    ciudad: "CABA",
    fuero: "Comercial",
    instancia: "Primera Instancia",
    direccion: "Marcelo T. de Alvear 1840, Piso 2",
    telefono: "(011) 4813-5678",
  },
  {
    id: "juz-lab-3-cordoba",
    nombre: "Juzgado de Conciliación y Trabajo de 3ª Nominación",
    provincia: "Córdoba",
    ciudad: "Córdoba",
    fuero: "Laboral",
    instancia: "Primera Instancia",
    direccion: "Arturo M. Bas 150",
    telefono: "(0351) 422-9876",
  },
  {
    id: "juz-pen-4-rosario",
    nombre: "Juzgado de 1ª Instancia en lo Penal de Sentencia Nº 4",
    provincia: "Santa Fe",
    ciudad: "Rosario",
    fuero: "Penal",
    instancia: "Primera Instancia",
    direccion: "Moreno 1050",
    telefono: "(0341) 472-1111",
  },
    {
    id: "cam-fed-5-mendoza",
    nombre: "Cámara Federal de Apelaciones de Mendoza",
    provincia: "Mendoza",
    ciudad: "Mendoza",
    fuero: "Federal",
    instancia: "Cámara",
    direccion: "España 123",
    telefono: "(0261) 449-5500",
  },
];

export const mockRatings: Rating[] = [
  {
    id: "rating-1",
    juzgadoId: "juz-civ-1-caba",
    usuarioId: "userhash1",
    puntuaciones: {
      eficiencia: 4,
      tiempoResolucion: 3,
      atencion: 5,
      organizacion: 4,
      accesibilidad: 5,
    },
    comentario: "Excelente atención por parte del personal de mesa de entradas. El proceso fue más rápido de lo esperado.",
    fechaExperiencia: "2023-10-15T00:00:00.000Z",
    fechaCalificacion: "2023-10-20T00:00:00.000Z",
  },
  {
    id: "rating-2",
    juzgadoId: "juz-civ-1-caba",
    usuarioId: "userhash2",
    puntuaciones: {
      eficiencia: 2,
      tiempoResolucion: 1,
      atencion: 3,
      organizacion: 2,
      accesibilidad: 4,
    },
    comentario: "Mucha demora en la resolución de expedientes simples. La organización interna parece caótica.",
    fechaExperiencia: "2023-09-01T00:00:00.000Z",
    fechaCalificacion: "2023-09-05T00:00:00.000Z",
  },
  {
    id: "rating-3",
    juzgadoId: "juz-com-2-caba",
    usuarioId: "userhash3",
    puntuaciones: {
      eficiencia: 5,
      tiempoResolucion: 5,
      atencion: 5,
      organizacion: 5,
      accesibilidad: 5,
    },
    comentario: "Un juzgado modelo. Eficientes, organizados y con un trato impecable. Resoluciones en tiempo récord.",
    fechaExperiencia: "2023-11-02T00:00:00.000Z",
    fechaCalificacion: "2023-11-03T00:00:00.000Z",
  },
  {
    id: "rating-4",
    juzgadoId: "juz-lab-3-cordoba",
    usuarioId: "userhash4",
    puntuaciones: {
      eficiencia: 3,
      tiempoResolucion: 2,
      atencion: 4,
      organizacion: 3,
      accesibilidad: 4,
    },
    comentario: "El personal es amable, pero los tiempos procesales son muy largos. La infraestructura es un poco antigua.",
    fechaExperiencia: "2023-08-20T00:00:00.000Z",
    fechaCalificacion: "2023-08-21T00:00:00.000Z",
  },
];
